### ISSUE TITLE
How to upgrade to React 16.3

### ISSUE THREAD

**Issue by WebMobi59** [CharlesStover/react-native-web-view#1]
I am trying to build iOS app with this package. but I am getting error.

**o.a.forwardRef is not a function.**

Any help is appreciated!

**Comment by quisido** [comment]
What version of react and react-native are you using?

**Comment by WebMobi59** [comment]
@CharlesStover, thanks for quick reply.

I am using react v16.0.0-alpha.12 and react native v0.46.0.

**Comment by quisido** [comment]
`forwardRef` wasn't supported until [16.3](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#forwardref-api), so you would need to upgrade your version of React to at least that version.

**Comment by WebMobi59** [comment]
could you possibly share package.json file?

**Comment by WebMobi59** [comment]
it would be appreciated if you can share some example.

**Comment by quisido** [comment]
Via command line, `yarn add react@^16.3.1` should fix it. If you are not using `yarn`, the `npm` equivalent would be `npm install react@^16.3.1 --save`.

You may need to upgrade `react-native` too, but I've had problems with the `react-native` package being finicky in the past, so I would only do that if the `react` upgrade by itself doesn't work.

**Comment by WebMobi59** [comment]
Okay, thank you.

**Comment by quisido** [comment]
You're welcome. If you need more assistance, you are welcome to ask here, but a React Native group may be better equipped to answer your questions regarding the upgrade process.
