### ISSUE TITLE
Error: "Setting onMessage on a Webview overrides existing values of window.postMessage..."

### ISSUE THREAD

**Issue by iamnader** [CharlesStover/react-native-web-view#2]
Hi there, seeing the same error I did with a normal WebView component with this package.

With the regular WebView I got around this error by patching postMessage.  The error went away but the postMessage didn't work.

Thoughts?

I'm using a WebView to load Stripe Connect, so just html, no url.

Thanks

**Comment by quisido** [comment]
Do you have a minimal reproduction of this error? I'm not familiar with how to encounter it.

**Comment by iamnader** [comment]
This issue is resolved in the latest react native community webview.  So closing this issue.
